# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vg3KD5Z98ciBaqp5eu1rwTK_HtKBow-7
"""

v1 = 10
v2 = 20

v3 = v1
v1 = v2
v2 = v3

print("v1 =", v1)
print("v2 =", v2)