# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vg3KD5Z98ciBaqp5eu1rwTK_HtKBow-7
"""

juros = 1.01
saldo = 500.0


saldo *= juros
saldo *= juros
saldo *= juros

print("Após 3 meses meu novo saldo é")
print(saldo)