# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vg3KD5Z98ciBaqp5eu1rwTK_HtKBow-7
"""

texto = "O resultado é:"
n1 = 10
n2 = 3.5

n3 = n1 + n2

print("Conteúdo de texto:", texto, " Tipo:", type(texto))
print("Conteúdo de n1:", n1, " Tipo:", type(n1))
print("Conteúdo de n2:", n2, " Tipo:", type(n2))
print("Resultado da soma:", n3, " Tipo:", type(n3))