# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vg3KD5Z98ciBaqp5eu1rwTK_HtKBow-7
"""

v1 = 5
v2 = 2

print("Tipo de valor1:", type(v1))
print("Tipo de valor2:", type(v2))

v3 = (v1/v2)

print("Resultado da divisão:", v3)
print("Tipo de resultado:", type(v3))